# This workflow will test IS for OIDC conformance
# 

name: OIDC Conformance Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'product-is tag name'
        required: true
        default: 'v5.12.0-m6'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: './product-is'
    - name: ls
      run: ls
