# This workflow will test IS for OIDC conformance
# 

name: OIDC Conformance Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'product-is tag name'
        required: true
        default: 'v5.12.0-m6'
      send-notification:
        description: 'send google chat notification'
        required: true
        default: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: './product-is'
        
   
    
    - name: Send Google Chat Notification
      if: always()
      run: |
        INPUT=${{github.event.inputs.send-notification}}
        SEND_NOTIFICATION=${INPUT^^}
        if [ $SEND_NOTIFICATION == "TRUE" ]; then
          CONFORMANCE_SUITE_URL=https://localhost:8443
          sudo python3 ./product-is/oidc-conformance-tests/send_notification.py $CONFORMANCE_SUITE_URL $GITHUB_RUN_NUMBER ${{job.status}} ${{github.repository}} ${{github.run_id}} ${{secrets.GOOGLE_WEBHOOK}}
        elif [ $SEND_NOTIFICATION == "FALSE" ]; then
          echo "========================================"
          echo "Skipped sending google chat notification"
          echo "========================================"
        else
          echo "================================================================="
          echo "Invalid parameter value. Skipped sending google chat notification"
          echo "================================================================="
        fi
       
   
    
